---
- name: "define virtual machine"
  virt:
    name: "{{ vm_name }}"
    command: define
    xml: "{{ lookup('template', 'redhat-template.xml.j2') }}"
    uri: "{{ kvm_uri }}"

- name: "start virtual machine"
  virt:
    name: "{{ vm_name }}"
    state: running
    uri: "{{ kvm_uri }}"